[env]
TERM="xterm-256color"

[general]
import = [
  "~/.dotfiles/alacritty/themes/everforest-dark-hard.toml",
]

# Font configuration
[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"
size = 11.0
offset.x = 0
offset.y = -2
glyph_offset.x = 0
glyph_offset.y = 0

# window configuration
[window]
opacity = 1
dynamic_padding = false
padding.x = 4
padding.y = 4
[window.dimensions]
columns = 120
lines = 40
