# Font configuration
[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"
size = 11.0
offset.x = 0
offset.y = -2
glyph_offset.x = 0
glyph_offset.y = 0

# window configuration
[window]
opacity = 1
dynamic_padding = false
padding.x = 0
padding.y = 0
[window.dimensions]
columns = 120
lines = 40

# [colors.primary]
# background = "0x282828"
# foreground = "0xdfbf8e"
# 
# [colors.normal]
# black = "0x665c54"
# red = "0xea6962"
# green = "0xa9b665"
# yellow = "0xe78a4e"
# blue = "0x7daea3"
# magenta = "0xd3869b"
# cyan = "0x89b482"
# white = "0xdfbf8e"
# 
# [colors.bright]
# black = "0x928374"
# red = "0xea6962"
# green = "0xa9b665"
# yellow = "0xe3a84e"
# blue = "0x7daea3"
# magenta = "0xd3869b"
# cyan = "0x89b482"
# white = "0xdfbf8e"

